import Foundation
import XCTest
@testable import OffsendRuntime

/// `offsend check --policy` behavior for repositories managed via `.offsend.yml`:
/// with `ignore.commit: false` the AI ignore files are gitignored and generated
/// locally, so their absence must not be reported as a policy failure.
final class OffsendCheckPolicyConfigTests: XCTestCase {
    private var root: URL!

    override func setUpWithError() throws {
        try super.setUpWithError()
        root = FileManager.default.temporaryDirectory
            .appendingPathComponent("check-policy-config-\(UUID().uuidString)", isDirectory: true)
        try FileManager.default.createDirectory(at: root, withIntermediateDirectories: true)
    }

    override func tearDown() {
        try? FileManager.default.removeItem(at: root)
        super.tearDown()
    }

    private var context: OffsendRuntimeContext {
        OffsendRuntimeContext(settings: .default, customDictionaries: [])
    }

    private func runPolicyCheck() async -> CheckReport {
        let service = OffsendCheckService(context: context)
        return await service.run(
            OffsendCheckRequest(
                fileURLs: [],
                policyDirectoryURL: root,
                workingDirectory: root
            )
        )
    }

    private func writeConfig(_ ignoreSection: String) throws {
        try """
        version: 1

        \(ignoreSection)
        """.write(
            to: root.appendingPathComponent(".offsend.yml"),
            atomically: true,
            encoding: .utf8
        )
    }

    func testMissingIgnoreFilesFailWithoutProjectConfig() async {
        let report = await runPolicyCheck()

        XCTAssertTrue(
            report.policyFindings.contains {
                $0.message.contains(".cursorignore") && $0.status == .fail
            },
            "Without .offsend.yml missing ignore files stay failures: \(report.policyFindings)"
        )
    }

    func testMissingManagedIgnoreFilesAreNotErrorsWhenConfigKeepsThemOutOfGit() async throws {
        try writeConfig(
            """
            ignore:
              commit: false
              patterns:
                - ".env*"
            """
        )

        let report = await runPolicyCheck()

        XCTAssertFalse(
            report.policyFindings.contains {
                $0.message.contains(".cursorignore") || $0.message.contains(".claudeignore")
            },
            "Managed ignore files are generated by `offsend sync`: \(report.policyFindings)"
        )
        XCTAssertFalse(
            report.policyFindings.contains { $0.status == .fail },
            "No failures expected for a managed repository: \(report.policyFindings)"
        )
        XCTAssertFalse(
            report.policyFindings.contains { $0.message.contains("Workspace policy status") },
            "Fallback status finding must not resurface skipped managed files: \(report.policyFindings)"
        )
    }

    func testMissingIgnoreFilesStillFailWhenConfigCommitsThem() async throws {
        try writeConfig(
            """
            ignore:
              commit: true
              patterns: []
            """
        )

        let report = await runPolicyCheck()

        XCTAssertTrue(
            report.policyFindings.contains {
                $0.message.contains(".cursorignore") && $0.status == .fail
            },
            "With ignore.commit: true the files belong in git: \(report.policyFindings)"
        )
    }

    func testIgnoreToolsNarrowingLimitsPolicyFindings() async throws {
        try writeConfig(
            """
            ignore:
              commit: true
              tools:
                - cursor
              patterns: []
            """
        )

        let report = await runPolicyCheck()

        XCTAssertTrue(
            report.policyFindings.contains { $0.message.contains(".cursorignore") },
            "Narrowed tool keeps its findings: \(report.policyFindings)"
        )
        XCTAssertFalse(
            report.policyFindings.contains { $0.message.contains(".claudeignore") },
            "Tools outside ignore.tools are not audited: \(report.policyFindings)"
        )
    }
}
